---
abstract: 'CSS parser class for Template::Flute'
author:
  - 'Stefan Hornburg (Racke) <racke@linuxia.de>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Flute-Style-CSS
no_index:
  directory:
    - t
    - inc
requires:
  CSS::Tiny: 0
  Template::Flute: 0.0081
  Test::More: 0
resources:
  bugtracker: https://github.com/racke/Template-Flute/issues
  repository: https://github.com/racke/Template-Flute.git
version: 0.0081
